# Generated by Django 5.2.4 on 2025-09-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coursedb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(default='+91', max_length=5)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, choices=[('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Madurai', 'Madurai'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Salem', 'Salem'), ('Tirunelveli', 'Tirunelveli'), ('Tiruppur', 'Tiruppur'), ('Vellore', 'Vellore'), ('Erode', 'Erode'), ('Thoothukudi', 'Thoothukudi'), ('Dindigul', 'Dindigul'), ('Thanjavur', 'Thanjavur'), ('Ranipet', 'Ranipet'), ('Sivakasi', 'Sivakasi'), ('Karur', 'Karur'), ('Udhagamandalam', 'Udhagamandalam'), ('Hosur', 'Hosur'), ('Nagercoil', 'Nagercoil'), ('Kanchipuram', 'Kanchipuram'), ('Kumarapalayam', 'Kumarapalayam'), ('Karaikkudi', 'Karaikkudi'), ('Neyveli', 'Neyveli'), ('Cuddalore', 'Cuddalore'), ('Tiruvannamalai', 'Tiruvannamalai'), ('Pollachi', 'Pollachi'), ('Rajapalayam', 'Rajapalayam'), ('Gudiyatham', 'Gudiyatham'), ('Pudukkottai', 'Pudukkottai'), ('Vaniyambadi', 'Vaniyambadi'), ('Ambur', 'Ambur'), ('Nagapattinam', 'Nagapattinam'), ('Others', 'Others')], max_length=100, null=True)),
                ('other_location', models.CharField(blank=True, max_length=100, null=True)),
                ('years_of_experience', models.FloatField(default=0.0)),
                ('employment_type', models.CharField(choices=[('FT', 'Full Time'), ('FL', 'Freelancer')], max_length=2)),
                ('date_of_joining', models.DateField(auto_now_add=True, null=True)),
                ('timing_slots', models.JSONField(blank=True, default=list, null=True)),
                ('mode_of_delivery', models.CharField(blank=True, max_length=100, null=True)),
                ('availability', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.FileField(blank=True, null=True, upload_to='trainer_profiles/')),
                ('demo_link', models.URLField(blank=True, null=True)),
                ('commercials', models.JSONField(blank=True, default=list, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stack', models.ManyToManyField(blank=True, to='coursedb.course')),
            ],
        ),
    ]
