# Generated by Django 5.2.4 on 2025-08-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainersdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
