# Generated by Django 5.2.4 on 2025-07-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainersdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='date_of_joining',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
