# Generated by Django 5.2.4 on 2025-08-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainersdb', '0002_alter_trainer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
