# Generated by Django 5.2.4 on 2025-12-26 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainersdb', '0002_trainerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='last_update_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_last_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
