# Generated by Django 5.2.4 on 2025-08-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedb', '0005_coursemodule_has_topics_topic'),
        ('trainersdb', '0003_alter_trainer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='trainer_type',
            new_name='employment_type',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='trainer',
            name='availability',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='country_code',
            field=models.CharField(default='+91', max_length=5),
        ),
        migrations.AddField(
            model_name='trainer',
            name='location',
            field=models.CharField(blank=True, choices=[('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Madurai', 'Madurai'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Salem', 'Salem'), ('Tirunelveli', 'Tirunelveli'), ('Tiruppur', 'Tiruppur'), ('Vellore', 'Vellore'), ('Erode', 'Erode'), ('Thoothukudi', 'Thoothukudi'), ('Dindigul', 'Dindigul'), ('Thanjavur', 'Thanjavur'), ('Ranipet', 'Ranipet'), ('Sivakasi', 'Sivakasi'), ('Karur', 'Karur'), ('Udhagamandalam', 'Udhagamandalam'), ('Hosur', 'Hosur'), ('Nagercoil', 'Nagercoil'), ('Kanchipuram', 'Kanchipuram'), ('Kumarapalayam', 'Kumarapalayam'), ('Karaikkudi', 'Karaikkudi'), ('Neyveli', 'Neyveli'), ('Cuddalore', 'Cuddalore'), ('Tiruvannamalai', 'Tiruvannamalai'), ('Pollachi', 'Pollachi'), ('Rajapalayam', 'Rajapalayam'), ('Gudiyatham', 'Gudiyatham'), ('Pudukkottai', 'Pudukkottai'), ('Vaniyambadi', 'Vaniyambadi'), ('Ambur', 'Ambur'), ('Nagapattinam', 'Nagapattinam'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='mode',
            field=models.CharField(blank=True, choices=[('WE', 'Weekend'), ('WD', 'Weekday'), ('WEWD', 'Weekend/Weekday'), ('Hybrid', 'Hybrid')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='other_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='stack',
        ),
        migrations.AddField(
            model_name='trainer',
            name='stack',
            field=models.ManyToManyField(blank=True, to='coursedb.course'),
        ),
    ]
