# Generated by Django 5.2.4 on 2025-08-07 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainersdb', '0004_rename_trainer_type_trainer_employment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='trainersdb.trainer')),
            ],
        ),
    ]
