# Generated by Django 5.2.4 on 2025-08-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainersdb', '0005_trainertiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='timing_slots',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.DeleteModel(
            name='TrainerTiming',
        ),
    ]
