# Generated by Django 5.2.4 on 2025-08-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainersdb', '0006_trainer_timing_slots_delete_trainertiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='commercials',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='demo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='trainer_profiles/'),
        ),
    ]
