# Generated by Django 5.2.4 on 2025-08-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainersdb', '0008_trainer_timing_slots_old_remove_trainer_timing_slots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='timing_slots_old',
        ),
    ]
