# Generated by Django 5.2.4 on 2025-08-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchdb', '0006_alter_batch_time_slot'),
        ('trainersdb', '0009_remove_trainer_timing_slots_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='timing_slots',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.AddField(
            model_name='trainer',
            name='timing_slots',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
