# Generated by Django 5.2.4 on 2025-08-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainersdb', '0010_remove_trainer_timing_slots_delete_timeslot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='mode',
        ),
    ]
