# Generated by Django 5.2.4 on 2025-08-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainersdb', '0011_remove_trainer_availability_remove_trainer_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='availability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='mode_of_delivery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
