# Generated by Django 5.2.4 on 2025-08-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainersdb', '0012_trainer_availability_trainer_mode_of_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='years_of_experience',
            field=models.FloatField(default=0.0),
        ),
    ]
