# Generated by Django 5.2.4 on 2025-08-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainersdb', '0013_alter_trainer_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
