# Generated by Django 5.2.4 on 2025-09-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0020_alter_student_pgdegree_alter_student_ugdegree'),
        ('studentsdb', '0025_student_certificate_issued_and_more'),
    ]

    operations = [
    ]
