# Generated by Django 5.2.4 on 2025-07-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursedb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodule',
            old_name='parent_course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='coursemodule',
            old_name='module_name',
            new_name='name',
        ),
    ]
