# Generated by Django 5.2.4 on 2025-09-24 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_duration',
            field=models.DecimalField(decimal_places=2, help_text='Duration in hours', max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='module_duration',
            field=models.DecimalField(decimal_places=2, help_text='Duration in hours', max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_duration',
            field=models.DecimalField(decimal_places=2, help_text='Duration in hours', max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
