# Generated by Django 5.2.4 on 2025-07-25 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedb', '0002_rename_parent_course_coursemodule_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='coursedb.course'),
        ),
    ]
