# Generated by Django 5.2.4 on 2025-09-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedb', '0003_alter_course_total_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_duration',
            field=models.DecimalField(decimal_places=2, help_text='Duration in hours', max_digits=4),
        ),
    ]
