# Generated by Django 5.2.4 on 2025-07-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedb', '0003_alter_coursemodule_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
