# Generated by Django 5.2.4 on 2025-07-26 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedb', '0004_course_code_coursecategory_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='has_topics',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('topic_duration', models.IntegerField(help_text='Duration in hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='coursedb.coursemodule')),
            ],
        ),
    ]
