# Generated by Django 5.2.4 on 2025-09-24 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedb', '0004_alter_course_total_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_duration',
            field=models.DecimalField(decimal_places=2, help_text='Duration in hours', max_digits=8),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='module_duration',
            field=models.DecimalField(decimal_places=2, help_text='Duration in hours', max_digits=8, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_duration',
            field=models.DecimalField(decimal_places=2, help_text='Duration in hours', max_digits=8, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
    ]
