# Generated by Django 5.2.4 on 2025-09-10 03:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coursedb', '0001_initial'),
        ('studentsdb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('portal', models.CharField(choices=[('naukri', 'Naukri'), ('linkedin', 'LinkedIn'), ('glassdoor', 'Glassdoor'), ('indeed', 'Indeed'), ('placement_india', 'Placement India'), ('freshersworld', 'Freshersworld'), ('shine', 'Shine'), ('many_jobs', 'Many Jobs'), ('internshala', 'Internshala'), ('quickr_jobs', 'Quickr Jobs'), ('google_jobs', 'Google Jobs'), ('monster', 'Monster'), ('company_website', 'Company Website'), ('others', 'Others')], max_length=100)),
                ('other_portal', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('spoc', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(choices=[('chennai', 'Chennai'), ('bangalore', 'Bangalore'), ('hyderabad', 'Hyderabad'), ('others', 'Others')], max_length=255)),
                ('other_location', models.CharField(blank=True, max_length=255, null=True)),
                ('progress', models.CharField(choices=[('resume_shared', 'Resume Shared'), ('interview_scheduling', 'Interview Scheduling'), ('interview_not_conducted', 'Interview Not Conducted'), ('interview_completed', 'Interview Completed')], default='resume_shared', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview_cycles', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('applying_role', models.CharField(max_length=255)),
                ('interview_round', models.CharField(choices=[('aptitude', 'Aptitude'), ('gd', 'Group Discussion'), ('technical', 'Technical'), ('hr', 'HR'), ('task', 'Task Work')], max_length=50)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(choices=[('chennai', 'Chennai'), ('bangalore', 'Bangalore'), ('hyderabad', 'Hyderabad'), ('others', 'Others')], max_length=255)),
                ('other_location', models.CharField(blank=True, max_length=255, null=True)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle_number', models.PositiveIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_interviews', to='placementdrive.company')),
                ('courses', models.ManyToManyField(to='coursedb.course')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_rounds', to='placementdrive.interview')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('not_attended', 'Not Attended'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('placed', 'Placed')], default='in_progress', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_status', to='placementdrive.interview')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_statuses', to='studentsdb.student')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSharedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('position_closed', 'Position Closed'), ('not_shortlisted', 'Not Shortlisted'), ('no_response', 'No Response'), ('interview_stage', 'Interview Stage')], max_length=50)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('resumes_shared', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_shared_statuses', to='placementdrive.company')),
                ('courses', models.ManyToManyField(related_name='resume_shared_statuses', to='coursedb.course')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
