# Generated by Django 5.2.4 on 2025-08-05 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdrive', '0001_initial'),
        ('studentsdb', '0021_alter_student_pgpassout_alter_student_ugpassout'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentsdb.coursecategory'),
        ),
    ]
