# Generated by Django 5.2.4 on 2025-08-14 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedb', '0005_coursemodule_has_topics_topic'),
        ('placementdrive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyingrole',
            name='course',
        ),
        migrations.AddField(
            model_name='applyingrole',
            name='courses',
            field=models.ManyToManyField(to='coursedb.course'),
        ),
        migrations.AddField(
            model_name='applyingrole',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applyingrole',
            name='salary',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
