# Generated by Django 5.2.4 on 2025-08-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdrive', '0002_remove_applyingrole_course_applyingrole_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='progress',
            field=models.CharField(choices=[('resume_shared', 'Resume Shared'), ('interview_scheduling', 'Interview Scheduling'), ('interview_completed', 'Interview Completed')], default='resume_shared', max_length=50),
        ),
    ]
