# Generated by Django 5.2.4 on 2025-08-19 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedb', '0005_coursemodule_has_topics_topic'),
        ('placementdrive', '0003_company_progress'),
        ('studentsdb', '0025_alter_student_pgdegree_alter_student_ugdegree'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_round', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('other_location', models.CharField(blank=True, max_length=255, null=True)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applying_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placementdrive.applyingrole')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_interviews', to='placementdrive.company')),
                ('courses', models.ManyToManyField(to='coursedb.course')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(to='studentsdb.student')),
            ],
        ),
    ]
