# Generated by Django 5.2.4 on 2025-08-09 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdrive', '0003_alter_placementdrive_stack'),
        ('studentsdb', '0023_remove_student_course_student_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementdrive',
            name='stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentsdb.coursecategory'),
        ),
    ]
