# Generated by Django 5.2.4 on 2025-08-13 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedb', '0005_coursemodule_has_topics_topic'),
        ('placementdrive', '0004_alter_placementdrive_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementdrive',
            name='stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursedb.coursecategory'),
        ),
    ]
