# Generated by Django 5.2.4 on 2025-08-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdb', '0006_alter_companyinterview_applying_for'),
        ('placementdrive', '0004_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='applying_role',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_round',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('aptitude', 'Aptitude'), ('technical', 'Technical'), ('hr', 'HR'), ('task', 'Task')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interview',
            name='location',
            field=models.CharField(choices=[('chennai', 'Chennai'), ('bangalore', 'Bangalore'), ('hyderabad', 'Hyderabad'), ('others', 'Others')], max_length=255),
        ),
        migrations.AlterField(
            model_name='interview',
            name='students',
            field=models.ManyToManyField(related_name='scheduled_interviews', to='studentsdb.student'),
        ),
        migrations.DeleteModel(
            name='ApplyingRole',
        ),
    ]
