# Generated by Django 5.2.4 on 2025-08-19 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdrive', '0005_alter_interview_applying_role_and_more'),
        ('studentsdb', '0025_alter_student_pgdegree_alter_student_ugdegree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='students',
        ),
        migrations.AddField(
            model_name='interview',
            name='parent_interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_rounds', to='placementdrive.interview'),
        ),
        migrations.AddField(
            model_name='interview',
            name='round_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='InterviewStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_status', to='placementdrive.interview')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsdb.student')),
            ],
        ),
    ]
