# Generated by Django 5.2.4 on 2025-08-19 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdrive', '0006_remove_interview_students_interview_parent_interview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_statuses', to='studentsdb.student'),
        ),
    ]
