# Generated by Django 5.2.4 on 2025-08-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdrive', '0007_alter_interviewstudent_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewstudent',
            name='selected',
        ),
        migrations.AddField(
            model_name='interviewstudent',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='offer_letters/'),
        ),
        migrations.AddField(
            model_name='interviewstudent',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('placed', 'Placed')], default='in_progress', max_length=20),
        ),
    ]
