# Generated by Django 5.2.4 on 2025-08-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdrive', '0008_remove_interviewstudent_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='other_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='other_portal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='venue',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(choices=[('chennai', 'Chennai'), ('bangalore', 'Bangalore'), ('hyderabad', 'Hyderabad'), ('others', 'Others')], max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='portal',
            field=models.CharField(choices=[('naukri', 'Naukri'), ('linkedin', 'LinkedIn'), ('glassdoor', 'Glassdoor'), ('indeed', 'Indeed'), ('placement_india', 'Placement India'), ('freshersworld', 'Freshersworld'), ('shine', 'Shine'), ('many_jobs', 'Many Jobs'), ('internshala', 'Internshala'), ('quickr_jobs', 'Quickr Jobs'), ('google_jobs', 'Google Jobs'), ('monster', 'Monster'), ('company_website', 'Company Website'), ('others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='progress',
            field=models.CharField(choices=[('resume_shared', 'Resume Shared'), ('interview_scheduling', 'Interview Scheduling'), ('interview_not_conducted', 'Interview Not Conducted'), ('interview_completed', 'Interview Completed')], default='resume_shared', max_length=50),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_round',
            field=models.CharField(choices=[('aptitude', 'Aptitude'), ('gd', 'Group Discussion'), ('technical', 'Technical'), ('hr', 'HR'), ('task', 'Task Work')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewstudent',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('not_attended', 'Not Attended'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('placed', 'Placed')], default='in_progress', max_length=20),
        ),
    ]
