# Generated by Django 5.2.4 on 2025-08-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdrive', '0010_alter_company_email_alter_company_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='interview_cycles',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
