# Generated by Django 5.2.4 on 2025-08-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdrive', '0011_company_interview_cycles'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='cycle_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
