# Generated by Django 5.2.4 on 2025-08-24 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdrive', '0012_interview_cycle_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSharedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('position_closed', 'Position Closed'), ('not_shortlisted', 'Not Shortlisted'), ('no_response', 'No Response')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_shared_statuses', to='placementdrive.company')),
            ],
        ),
    ]
