# Generated by Django 5.2.4 on 2025-08-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdrive', '0013_resumesharedstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumesharedstatus',
            name='resumes_shared',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='resumesharedstatus',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
