# Generated by Django 5.2.4 on 2025-09-05 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedb', '0005_coursemodule_has_topics_topic'),
        ('placementdrive', '0014_resumesharedstatus_resumes_shared_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumesharedstatus',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='resumesharedstatus',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_shared_statuses', to='coursedb.course'),
        ),
    ]
