# Generated by Django 5.2.4 on 2025-09-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdrive', '0015_alter_resumesharedstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumesharedstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('position_closed', 'Position Closed'), ('not_shortlisted', 'Not Shortlisted'), ('no_response', 'No Response')], max_length=50),
        ),
    ]
