# Generated by Django 5.2.4 on 2025-09-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedb', '0005_coursemodule_has_topics_topic'),
        ('placementdrive', '0016_alter_resumesharedstatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumesharedstatus',
            name='course',
        ),
        migrations.AddField(
            model_name='resumesharedstatus',
            name='courses',
            field=models.ManyToManyField(related_name='resume_shared_statuses', to='coursedb.course'),
        ),
        migrations.AlterField(
            model_name='resumesharedstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('position_closed', 'Position Closed'), ('not_shortlisted', 'Not Shortlisted'), ('no_response', 'No Response'), ('interview_stage', 'Interview Stage')], max_length=50),
        ),
    ]
