# Generated by Django 5.2.4 on 2025-07-17 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentsdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('feedback', models.TextField(blank=True)),
                ('company_1', models.CharField(blank=True, max_length=255)),
                ('company_2', models.CharField(blank=True, max_length=255)),
                ('company_3', models.CharField(blank=True, max_length=255)),
                ('company_4', models.CharField(blank=True, max_length=255)),
                ('company_5', models.CharField(blank=True, max_length=255)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='studentsdb.student')),
            ],
        ),
    ]
