# Generated by Django 5.2.4 on 2025-09-10 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placementdrive', '0001_initial'),
        ('studentsdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_link', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('is_active', models.BooleanField(default=True)),
                ('reason_for_inactive', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='studentsdb.student')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applying_for', models.CharField(max_length=255, null=True)),
                ('interview_round', models.CharField(choices=[('virtual', 'Virtual'), ('aptitude', 'Aptitude'), ('technical', 'Technical'), ('hr', 'HR'), ('task', 'Task')], default='virtual', max_length=50)),
                ('location', models.CharField(choices=[('chennai', 'Chennai'), ('bangalore', 'Bangalore'), ('hyderabad', 'Hyderabad'), ('others', 'Others')], max_length=255, null=True)),
                ('other_location', models.CharField(blank=True, max_length=255, null=True)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('attended', models.BooleanField(default=False)),
                ('selected', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='placementdrive.company')),
                ('students', models.ManyToManyField(related_name='interviews', to='studentsdb.student')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='placementdb.placement')),
            ],
        ),
    ]
