# Generated by Django 5.2.4 on 2025-08-14 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placementdrive', '0001_initial'),
        ('studentsdb', '0024_delete_course_delete_coursecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_link', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='studentsdb.student')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('chennai', 'Chennai'), ('bangalore', 'Bangalore'), ('hyderabad', 'Hyderabad'), ('others', 'Others')], max_length=255, null=True)),
                ('other_location', models.CharField(blank=True, max_length=255, null=True)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('attended', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('applying_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='placementdrive.applyingrole')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='placementdrive.company')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='placementdb.placement')),
            ],
        ),
    ]
