# Generated by Django 5.2.4 on 2025-09-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='std_professional_photo',
            field=models.ImageField(blank=True, null=True, upload_to='professional_photos/'),
        ),
    ]
