# Generated by Django 5.2.4 on 2025-07-29 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='company_1',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='company_2',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='company_3',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='company_4',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='company_5',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='feedback',
        ),
        migrations.CreateModel(
            name='CompanyInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_location', models.CharField(blank=True, max_length=255)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('attended', models.BooleanField(default=False)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='placementdb.placement')),
            ],
        ),
    ]
