# Generated by Django 5.2.4 on 2025-08-14 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placementdb', '0002_fake_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInterview',
        ),
    ]
