# Generated by Django 5.2.4 on 2025-07-31 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdb', '0002_remove_placement_company_1_and_more'),
        ('placementdrive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinterview',
            name='company_location',
        ),
        migrations.RemoveField(
            model_name='companyinterview',
            name='company_name',
        ),
        migrations.AddField(
            model_name='companyinterview',
            name='applying_for',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyinterview',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='placementdrive.placementdrive'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='resume_link',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
