# Generated by Django 5.2.4 on 2025-07-31 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdb', '0002_remove_placement_company_1_and_more'),
        ('placementdrive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='resume_link',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
