# Generated by Django 5.2.4 on 2025-08-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdb', '0004_companyinterview'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinterview',
            name='interview_round',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('aptitude', 'Aptitude'), ('technical', 'Technical'), ('hr', 'HR'), ('task', 'Task')], default='virtual', max_length=50),
        ),
        migrations.AddField(
            model_name='companyinterview',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyinterview',
            name='students',
            field=models.ManyToManyField(related_name='interviews', to='studentsdb.student'),
        ),
    ]
