# Generated by Django 5.2.4 on 2025-08-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdb', '0005_companyinterview_interview_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinterview',
            name='applying_for',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
