# Generated by Django 5.2.4 on 2025-09-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdb', '0006_alter_companyinterview_applying_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='certificate_issued',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='mock_interview_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='placement_session_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='reason_for_inactive',
            field=models.TextField(blank=True, null=True),
        ),
    ]
