# Generated by Django 5.2.4 on 2025-09-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementdb', '0007_placement_certificate_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
