# Generated by Django 5.2.4 on 2025-09-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placementdb', '0008_placement_created_at_placement_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='certificate_issued',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='mock_interview_completed',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='placement_session_completed',
        ),
    ]
