# Generated by Django 5.2.4 on 2025-07-17 05:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultantdb', '0001_initial'),
        ('settingsdb', '0001_initial'),
        ('trainersdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('alternative_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('tentative_end_date', models.DateField(blank=True, null=True)),
                ('course_percentage', models.FloatField(default=0)),
                ('pl_required', models.BooleanField(default=False)),
                ('mode_of_class', models.CharField(choices=[('ON', 'Online'), ('OFF', 'Offline')], max_length=3)),
                ('week_type', models.CharField(choices=[('WD', 'Weekday'), ('WE', 'Weekend')], max_length=2)),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultantdb.consultant')),
                ('source_of_joining', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingsdb.sourceofjoining')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainersdb.trainer')),
            ],
        ),
    ]
