# Generated by Django 5.2.4 on 2025-09-10 03:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultantdb', '0001_initial'),
        ('settingsdb', '0001_initial'),
        ('trainersdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(default='+91', max_length=5)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('alternative_country_code', models.CharField(blank=True, default='+91', max_length=5)),
                ('alternative_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('ugdegree', models.CharField(blank=True, choices=[('Diploma', 'Diploma'), ('B.Tech / B.E.', 'B.Tech / B.E.'), ('B.Sc.', 'B.Sc.'), ('BCA', 'BCA (Bachelor of Computer Applications)'), ('BBA', 'BBA (Bachelor of Business Administration)'), ('BBM', 'BBM (Bachelor of Business Management)'), ('BMS', 'BMS (Bachelor of Management Studies)'), ('B.Com', 'B.Com (Commerce)'), ('MBBS', 'MBBS (Bachelor of Medicine and Bachelor of Surgery)'), ('BDS', 'BDS (Dental)'), ('BAMS', 'BAMS (Ayurveda)'), ('BHMS', 'BHMS (Homeopathy)'), ('B.Pharm', 'B.Pharm (Pharmacy)'), ('BPT', 'BPT (Physiotherapy)'), ('BA', 'BA (Arts & Humanities)'), ('BFA', 'BFA (Fine Arts)'), ('BPA', 'BPA (Performing Arts)'), ('B.Ed.', 'B.Ed. (Bachelor of Education)'), ('B.El.Ed.', 'B.El.Ed. (Elementary Education)'), ('BHM', 'BHM (Bachelor of Hotel Management)'), ('BA LLB / BBA LLB', 'BA LLB / BBA LLB'), ('LLB', 'LLB'), ('B.Des', 'B.Des (Bachelor of Design)'), ('BMM', 'BMM (Media and Mass Communication)'), ('BJMC', 'BJMC (Journalism and Mass Comm)'), ('B.Arch', 'B.Arch (Bachelor of Architecture)'), ('M.Tech / M.E.', 'M.Tech / M.E.'), ('M.Sc.', 'M.Sc.'), ('MCA', 'MCA (Master of Computer Applications)'), ('MBA', 'MBA (Master of Business Administration)'), ('M.Com', 'M.Com (Commerce)'), ('PGDM', 'PGDM (Post Graduate Diploma in Management)'), ('MD / MS', 'MD / MS (Medical Specializations)'), ('MDS', 'MDS (Dental Specializations)'), ('M.Pharm', 'M.Pharm (Pharmacy)'), ('MPT', 'MPT (Physiotherapy)'), ('M.Phil', 'M.Phil'), ('Ph.D.', 'Ph.D. (Doctorate)'), ('MA', 'MA (Arts & Humanities)'), ('MFA', 'MFA (Fine Arts)'), ('MSW', 'MSW (Master of Social Work)'), ('M.Ed.', 'M.Ed. (Master of Education)'), ('LLM', 'LLM (Master of Law)'), ('M.Des', 'M.Des (Master of Design)'), ('MJMC', 'MJMC (Master in Journalism and Mass Communication)'), ('M.Arch', 'M.Arch (Master of Architecture)')], max_length=100, null=True)),
                ('ugbranch', models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Information Technology', 'Information Technology'), ('AI/ML', 'AI/ML'), ('Robotics', 'Robotics'), ('Data Science', 'Data Science'), ('Accounting / Finance', 'Accounting / Finance'), ('Marketing', 'Marketing'), ('HR', 'HR'), ('Finance', 'Finance'), ('Analytics', 'Analytics'), ('Nursing', 'Nursing'), ('Pharmacy', 'Pharmacy'), ('Physiotherapy', 'Physiotherapy'), ('Biotechnology', 'Biotechnology'), ('Clinical Research / Public Health', 'Clinical Research / Public Health'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics'), ('Environmental Science', 'Environmental Science'), ('Microbiology / Zoology / Botany', 'Microbiology / Zoology / Botany'), ('English', 'English'), ('History', 'History'), ('Economics', 'Economics'), ('Sociology', 'Sociology'), ('Psychology', 'Psychology'), ('Political Science', 'Political Science'), ('Fine Arts', 'Fine Arts'), ('Performing Arts', 'Performing Arts'), ('Social Work', 'Social Work'), ('Education', 'Education'), ('Elementary Education', 'Elementary Education'), ('Aviation', 'Aviation'), ('Hotel Management', 'Hotel Management'), ('Aviation Management', 'Aviation Management'), ('Travel & Tourism', 'Travel & Tourism'), ('Law', 'Law'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('Fashion Design', 'Fashion Design'), ('UI/UX Design', 'UI/UX Design'), ('Industrial Design', 'Industrial Design'), ('Media and Mass Communication', 'Media and Mass Communication'), ('Journalism and Mass Comm', 'Journalism and Mass Comm'), ('STEM Programs', 'STEM Programs')], max_length=100, null=True)),
                ('ugpassout', models.IntegerField(blank=True, choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], null=True)),
                ('ugpercentage', models.FloatField(blank=True, null=True)),
                ('pgdegree', models.CharField(blank=True, choices=[('Diploma', 'Diploma'), ('B.Tech / B.E.', 'B.Tech / B.E.'), ('B.Sc.', 'B.Sc.'), ('BCA', 'BCA (Bachelor of Computer Applications)'), ('BBA', 'BBA (Bachelor of Business Administration)'), ('BBM', 'BBM (Bachelor of Business Management)'), ('BMS', 'BMS (Bachelor of Management Studies)'), ('B.Com', 'B.Com (Commerce)'), ('MBBS', 'MBBS (Bachelor of Medicine and Bachelor of Surgery)'), ('BDS', 'BDS (Dental)'), ('BAMS', 'BAMS (Ayurveda)'), ('BHMS', 'BHMS (Homeopathy)'), ('B.Pharm', 'B.Pharm (Pharmacy)'), ('BPT', 'BPT (Physiotherapy)'), ('BA', 'BA (Arts & Humanities)'), ('BFA', 'BFA (Fine Arts)'), ('BPA', 'BPA (Performing Arts)'), ('B.Ed.', 'B.Ed. (Bachelor of Education)'), ('B.El.Ed.', 'B.El.Ed. (Elementary Education)'), ('BHM', 'BHM (Bachelor of Hotel Management)'), ('BA LLB / BBA LLB', 'BA LLB / BBA LLB'), ('LLB', 'LLB'), ('B.Des', 'B.Des (Bachelor of Design)'), ('BMM', 'BMM (Media and Mass Communication)'), ('BJMC', 'BJMC (Journalism and Mass Comm)'), ('B.Arch', 'B.Arch (Bachelor of Architecture)'), ('M.Tech / M.E.', 'M.Tech / M.E.'), ('M.Sc.', 'M.Sc.'), ('MCA', 'MCA (Master of Computer Applications)'), ('MBA', 'MBA (Master of Business Administration)'), ('M.Com', 'M.Com (Commerce)'), ('PGDM', 'PGDM (Post Graduate Diploma in Management)'), ('MD / MS', 'MD / MS (Medical Specializations)'), ('MDS', 'MDS (Dental Specializations)'), ('M.Pharm', 'M.Pharm (Pharmacy)'), ('MPT', 'MPT (Physiotherapy)'), ('M.Phil', 'M.Phil'), ('Ph.D.', 'Ph.D. (Doctorate)'), ('MA', 'MA (Arts & Humanities)'), ('MFA', 'MFA (Fine Arts)'), ('MSW', 'MSW (Master of Social Work)'), ('M.Ed.', 'M.Ed. (Master of Education)'), ('LLM', 'LLM (Master of Law)'), ('M.Des', 'M.Des (Master of Design)'), ('MJMC', 'MJMC (Master in Journalism and Mass Communication)'), ('M.Arch', 'M.Arch (Master of Architecture)')], max_length=100, null=True)),
                ('pgbranch', models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Information Technology', 'Information Technology'), ('AI/ML', 'AI/ML'), ('Robotics', 'Robotics'), ('Data Science', 'Data Science'), ('Accounting / Finance', 'Accounting / Finance'), ('Marketing', 'Marketing'), ('HR', 'HR'), ('Finance', 'Finance'), ('Analytics', 'Analytics'), ('Nursing', 'Nursing'), ('Pharmacy', 'Pharmacy'), ('Physiotherapy', 'Physiotherapy'), ('Biotechnology', 'Biotechnology'), ('Clinical Research / Public Health', 'Clinical Research / Public Health'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics'), ('Environmental Science', 'Environmental Science'), ('Microbiology / Zoology / Botany', 'Microbiology / Zoology / Botany'), ('English', 'English'), ('History', 'History'), ('Economics', 'Economics'), ('Sociology', 'Sociology'), ('Psychology', 'Psychology'), ('Political Science', 'Political Science'), ('Fine Arts', 'Fine Arts'), ('Performing Arts', 'Performing Arts'), ('Social Work', 'Social Work'), ('Education', 'Education'), ('Elementary Education', 'Elementary Education'), ('Aviation', 'Aviation'), ('Hotel Management', 'Hotel Management'), ('Aviation Management', 'Aviation Management'), ('Travel & Tourism', 'Travel & Tourism'), ('Law', 'Law'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('Fashion Design', 'Fashion Design'), ('UI/UX Design', 'UI/UX Design'), ('Industrial Design', 'Industrial Design'), ('Media and Mass Communication', 'Media and Mass Communication'), ('Journalism and Mass Comm', 'Journalism and Mass Comm'), ('STEM Programs', 'STEM Programs')], max_length=100, null=True)),
                ('pgpassout', models.IntegerField(blank=True, choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], null=True)),
                ('pgpercentage', models.FloatField(blank=True, null=True)),
                ('working_status', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3)),
                ('it_experience', models.CharField(blank=True, choices=[('IT', 'IT'), ('NON-IT', 'Non-IT')], max_length=10, null=True)),
                ('course_status', models.CharField(choices=[('YTS', 'Yet to Start'), ('IP', 'In Progress'), ('C', 'Completed'), ('R', 'Refund'), ('D', 'Discontinued'), ('H', 'Hold'), ('P', 'Placed')], default='YTS', max_length=3)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('course_percentage', models.FloatField(default=0)),
                ('pl_required', models.BooleanField(default=False)),
                ('mode_of_class', models.CharField(choices=[('ON', 'Online'), ('OFF', 'Offline')], max_length=3)),
                ('week_type', models.CharField(choices=[('WD', 'Weekday'), ('WE', 'Weekend')], max_length=2)),
                ('mock_interview_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('placement_session_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('certificate_issued', models.BooleanField(blank=True, default=False, null=True)),
                ('onboardingcalldone', models.BooleanField(blank=True, default=False, null=True)),
                ('interviewquestion_shared', models.BooleanField(blank=True, default=False, null=True)),
                ('resume_template_shared', models.BooleanField(blank=True, default=False, null=True)),
                ('consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultantdb.consultant')),
                ('source_of_joining', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingsdb.sourceofjoining')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainersdb.trainer')),
            ],
        ),
    ]
