# Generated by Django 5.2.4 on 2025-07-11 06:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batchdb', '0001_initial'),
        ('trainersdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('tentative_end_date', models.DateField(blank=True, null=True)),
                ('course_percentage', models.FloatField(default=0)),
                ('pl_required', models.BooleanField(default=False)),
                ('source_of_joining', models.CharField(blank=True, max_length=100)),
                ('mode_of_class', models.CharField(choices=[('ON', 'Online'), ('OFF', 'Offline')], max_length=3)),
                ('week_type', models.CharField(choices=[('WD', 'Weekday'), ('WE', 'Weekend')], max_length=2)),
                ('consultant', models.CharField(blank=True, max_length=100)),
                ('payment_account', models.CharField(blank=True, max_length=100)),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_bill', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi_type', models.CharField(choices=[('NONE', 'None'), ('2', '2 EMI'), ('3', '3 EMI'), ('4', '4 EMI')], default='NONE', max_length=4)),
                ('emi_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emi_1_date', models.DateField(blank=True, null=True)),
                ('emi_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emi_2_date', models.DateField(blank=True, null=True)),
                ('emi_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emi_3_date', models.DateField(blank=True, null=True)),
                ('emi_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emi_4_date', models.DateField(blank=True, null=True)),
                ('total_pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='batchdb.batch')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainersdb.trainer')),
            ],
        ),
    ]
