# Generated by Django 5.2.4 on 2025-07-11 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='trainer',
        ),
    ]
