# Generated by Django 5.2.4 on 2026-01-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pgpassout',
            field=models.IntegerField(blank=True, choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031)], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ugpassout',
            field=models.IntegerField(blank=True, choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031)], null=True),
        ),
    ]
