# Generated by Django 5.2.4 on 2025-07-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emi_1_amount',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emi_1_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emi_2_amount',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emi_2_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emi_3_amount',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emi_3_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emi_4_amount',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emi_4_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emi_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gst_bill',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payment_account',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_fees',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_pending_amount',
        ),
    ]
