# Generated by Django 5.2.4 on 2025-07-11 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0002_remove_student_batch_remove_student_trainer'),
        ('trainersdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainersdb.trainer'),
        ),
    ]
