# Generated by Django 5.2.4 on 2026-01-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0003_studentconversation_conversationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='hashtag',
            field=models.CharField(blank=True, choices=[('placement', 'Placement'), ('class', 'Class'), ('payment', 'Payment')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='', max_length=10),
        ),
    ]
