# Generated by Django 5.0.6 on 2024-07-18 05:31

from django.db import migrations
from studentsdb.course_data import COURSE_CATEGORIES, COURSES

def populate_course_data(apps, schema_editor):
    CourseCategory = apps.get_model('studentsdb', 'CourseCategory')
    Course = apps.get_model('studentsdb', 'Course')

    for category_name in COURSE_CATEGORIES:
        CourseCategory.objects.get_or_create(name=category_name)

    for course_data in COURSES:
        category = CourseCategory.objects.get(name=course_data['category'])
        Course.objects.get_or_create(
            code=course_data['code'],
            defaults={
                'name': course_data['name'],
                'category': category
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0003_course_coursecategory_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_course_data),
    ]
