# Generated by Django 5.2.4 on 2025-07-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0003_student_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
