# Generated by Django 5.2.4 on 2025-07-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0004_populate_course_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pgbranch',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pgdegree',
            field=models.CharField(blank=True, choices=[('B.Tech', 'B.Tech'), ('B.E', 'B.E'), ('B.Sc', 'B.Sc'), ('BCA', 'BCA'), ('B.Com', 'B.Com'), ('M.Tech', 'M.Tech'), ('M.E', 'M.E'), ('M.Sc', 'M.Sc'), ('MCA', 'MCA'), ('M.Com', 'M.Com')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pgpassout',
            field=models.IntegerField(blank=True, choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ugbranch',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ugdegree',
            field=models.CharField(blank=True, choices=[('B.Tech', 'B.Tech'), ('B.E', 'B.E'), ('B.Sc', 'B.Sc'), ('BCA', 'BCA'), ('B.Com', 'B.Com'), ('M.Tech', 'M.Tech'), ('M.E', 'M.E'), ('M.Sc', 'M.Sc'), ('MCA', 'MCA'), ('M.Com', 'M.Com')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ugpassout',
            field=models.IntegerField(blank=True, choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], null=True),
        ),
    ]
