# Generated by Django 5.2.4 on 2025-07-15 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultantdb', '0001_initial'),
        ('studentsdb', '0004_student_alternative_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultantdb.consultant'),
        ),
    ]
