# Generated by Django 5.2.4 on 2026-01-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0004_conversationmessage_hashtag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='student_conversation/'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='file_mime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
