# Generated by Django 5.2.4 on 2026-01-27 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0006_conversationmessage_edited_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconversation',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentconversation',
            name='last_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentconversation',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentconversation',
            name='last_message_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentconversation',
            name='priority_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentconversation',
            name='unread_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
