# Generated by Django 5.2.4 on 2026-01-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0007_studentconversation_is_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconversation',
            name='last_message_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentconversation',
            name='last_message_priority_level',
            field=models.IntegerField(default=0),
        ),
    ]
