# Generated by Django 5.2.4 on 2025-07-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0007_alter_student_course_status'),
        ('studentsdb', '0008_update_course_names'),
    ]

    operations = [
    ]
