# Generated by Django 5.2.4 on 2026-01-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0008_studentconversation_last_message_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconversation',
            name='last_message_hashtag',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
