# Generated by Django 5.2.4 on 2026-01-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0009_studentconversation_last_message_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='hashtag',
            field=models.CharField(blank=True, choices=[('placement', 'Placement'), ('class', 'Class'), ('payment', 'Payment'), ('followups', 'Followups')], default='', max_length=20),
        ),
    ]
