# Generated by Django 5.2.4 on 2026-01-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0010_alter_conversationmessage_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='hashtag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentconversation',
            name='last_message_hashtag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
