# Generated by Django 5.2.4 on 2025-07-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0010_add_dotnet_react_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_status',
            field=models.CharField(choices=[('YTS', 'Yet to Start'), ('IP', 'In Progress'), ('C', 'Completed'), ('R', 'Refund'), ('D', 'Discontinued'), ('H', 'Hold'), ('P', 'Placed')], default='YTS', max_length=3),
        ),
    ]
