# Generated by Django 5.2.4 on 2026-01-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0011_alter_conversationmessage_hashtag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_status',
            field=models.CharField(choices=[('YTS', 'Yet to Start'), ('IP', 'In Progress'), ('C', 'Completed'), ('R', 'Refund'), ('D', 'Discontinued'), ('H', 'Hold'), ('P', 'Placed'), ('IA', 'In Active')], default='YTS', max_length=3),
        ),
    ]
