# Generated by Django 5.2.4 on 2025-07-19 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0012_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
