# Generated by Django 5.0.6 on 2025-07-19 17:00

from django.db import migrations

def update_terraform_course_name(apps, schema_editor):
    Course = apps.get_model('studentsdb', 'Course')
    
    # Update Cloud Course
    course_c308 = Course.objects.filter(code='C308').first()
    if course_c308 and course_c308.name != 'Terraform':
        course_c308.name = 'Terraform'
        course_c308.save()

    # Update Data Course
    course_c410 = Course.objects.filter(code='C410').first()
    if course_c410 and course_c410.name != 'Terraform':
        course_c410.name = 'Terraform'
        course_c410.save()

class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0012_alter_student_phone'),
    ]

    operations = [
        migrations.RunPython(update_terraform_course_name),
    ]