# Generated by Django 5.2.4 on 2025-07-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0013_alter_student_enrollment_date'),
        ('studentsdb', '0014_update_terraform_course_name'),
    ]

    operations = [
    ]
