# Generated by Django 5.0.6 on 2025-07-19 17:48

from django.db import migrations

def remove_duplicate_terraform(apps, schema_editor):
    Course = apps.get_model('studentsdb', 'Course')
    Course.objects.filter(code='C410').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0015_merge_20250719_2232'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_terraform),
    ]