# Generated by Django 5.2.4 on 2025-07-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0016_remove_duplicate_terraform'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='it_experience',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('NON-IT', 'Non-IT')], max_length=10, null=True),
        ),
    ]
