# Generated by Django 5.2.4 on 2025-07-23 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultantdb', '0006_achievement_goal'),
        ('settingsdb', '0001_initial'),
        ('studentsdb', '0017_student_it_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='consultant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultantdb.consultant'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='source_of_joining',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingsdb.sourceofjoining'),
        ),
    ]
