# Generated by Django 5.2.4 on 2025-08-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0021_alter_student_pgpassout_alter_student_ugpassout'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='alternative_country_code',
            field=models.CharField(blank=True, default='+91', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='country_code',
            field=models.CharField(default='+91', max_length=5),
        ),
    ]
