# Generated by Django 5.2.4 on 2025-08-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0022_student_alternative_country_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
