# Generated by Django 5.2.4 on 2025-08-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0023_remove_student_course_student_course_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
    ]
