# Generated by Django 5.2.4 on 2025-08-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0024_delete_course_delete_coursecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pgdegree',
            field=models.CharField(blank=True, choices=[('Diploma', 'Diploma'), ('B.Tech / B.E.', 'B.Tech / B.E.'), ('B.Sc.', 'B.Sc.'), ('BCA', 'BCA (Bachelor of Computer Applications)'), ('BBA', 'BBA (Bachelor of Business Administration)'), ('BBM', 'BBM (Bachelor of Business Management)'), ('BMS', 'BMS (Bachelor of Management Studies)'), ('B.Com', 'B.Com (Commerce)'), ('MBBS', 'MBBS (Bachelor of Medicine and Bachelor of Surgery)'), ('BDS', 'BDS (Dental)'), ('BAMS', 'BAMS (Ayurveda)'), ('BHMS', 'BHMS (Homeopathy)'), ('B.Pharm', 'B.Pharm (Pharmacy)'), ('BPT', 'BPT (Physiotherapy)'), ('BA', 'BA (Arts & Humanities)'), ('BFA', 'BFA (Fine Arts)'), ('BPA', 'BPA (Performing Arts)'), ('B.Ed.', 'B.Ed. (Bachelor of Education)'), ('B.El.Ed.', 'B.El.Ed. (Elementary Education)'), ('BHM', 'BHM (Bachelor of Hotel Management)'), ('BA LLB / BBA LLB', 'BA LLB / BBA LLB'), ('LLB', 'LLB'), ('B.Des', 'B.Des (Bachelor of Design)'), ('BMM', 'BMM (Media and Mass Communication)'), ('BJMC', 'BJMC (Journalism and Mass Comm)'), ('B.Arch', 'B.Arch (Bachelor of Architecture)'), ('M.Tech / M.E.', 'M.Tech / M.E.'), ('M.Sc.', 'M.Sc.'), ('MCA', 'MCA (Master of Computer Applications)'), ('MBA', 'MBA (Master of Business Administration)'), ('M.Com', 'M.Com (Commerce)'), ('PGDM', 'PGDM (Post Graduate Diploma in Management)'), ('MD / MS', 'MD / MS (Medical Specializations)'), ('MDS', 'MDS (Dental Specializations)'), ('M.Pharm', 'M.Pharm (Pharmacy)'), ('MPT', 'MPT (Physiotherapy)'), ('M.Phil', 'M.Phil'), ('Ph.D.', 'Ph.D. (Doctorate)'), ('MA', 'MA (Arts & Humanities)'), ('MFA', 'MFA (Fine Arts)'), ('MSW', 'MSW (Master of Social Work)'), ('M.Ed.', 'M.Ed. (Master of Education)'), ('LLM', 'LLM (Master of Law)'), ('M.Des', 'M.Des (Master of Design)'), ('MJMC', 'MJMC (Master in Journalism and Mass Communication)'), ('M.Arch', 'M.Arch (Master of Architecture)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ugdegree',
            field=models.CharField(blank=True, choices=[('Diploma', 'Diploma'), ('B.Tech / B.E.', 'B.Tech / B.E.'), ('B.Sc.', 'B.Sc.'), ('BCA', 'BCA (Bachelor of Computer Applications)'), ('BBA', 'BBA (Bachelor of Business Administration)'), ('BBM', 'BBM (Bachelor of Business Management)'), ('BMS', 'BMS (Bachelor of Management Studies)'), ('B.Com', 'B.Com (Commerce)'), ('MBBS', 'MBBS (Bachelor of Medicine and Bachelor of Surgery)'), ('BDS', 'BDS (Dental)'), ('BAMS', 'BAMS (Ayurveda)'), ('BHMS', 'BHMS (Homeopathy)'), ('B.Pharm', 'B.Pharm (Pharmacy)'), ('BPT', 'BPT (Physiotherapy)'), ('BA', 'BA (Arts & Humanities)'), ('BFA', 'BFA (Fine Arts)'), ('BPA', 'BPA (Performing Arts)'), ('B.Ed.', 'B.Ed. (Bachelor of Education)'), ('B.El.Ed.', 'B.El.Ed. (Elementary Education)'), ('BHM', 'BHM (Bachelor of Hotel Management)'), ('BA LLB / BBA LLB', 'BA LLB / BBA LLB'), ('LLB', 'LLB'), ('B.Des', 'B.Des (Bachelor of Design)'), ('BMM', 'BMM (Media and Mass Communication)'), ('BJMC', 'BJMC (Journalism and Mass Comm)'), ('B.Arch', 'B.Arch (Bachelor of Architecture)'), ('M.Tech / M.E.', 'M.Tech / M.E.'), ('M.Sc.', 'M.Sc.'), ('MCA', 'MCA (Master of Computer Applications)'), ('MBA', 'MBA (Master of Business Administration)'), ('M.Com', 'M.Com (Commerce)'), ('PGDM', 'PGDM (Post Graduate Diploma in Management)'), ('MD / MS', 'MD / MS (Medical Specializations)'), ('MDS', 'MDS (Dental Specializations)'), ('M.Pharm', 'M.Pharm (Pharmacy)'), ('MPT', 'MPT (Physiotherapy)'), ('M.Phil', 'M.Phil'), ('Ph.D.', 'Ph.D. (Doctorate)'), ('MA', 'MA (Arts & Humanities)'), ('MFA', 'MFA (Fine Arts)'), ('MSW', 'MSW (Master of Social Work)'), ('M.Ed.', 'M.Ed. (Master of Education)'), ('LLM', 'LLM (Master of Law)'), ('M.Des', 'M.Des (Master of Design)'), ('MJMC', 'MJMC (Master in Journalism and Mass Communication)'), ('M.Arch', 'M.Arch (Master of Architecture)')], max_length=100, null=True),
        ),
    ]
