# Generated by Django 5.2.4 on 2025-07-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultantdb', '0004_alter_consultant_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consultant',
            table='consultantdb_consultant',
        ),
    ]
