# Generated by Django 5.2.4 on 2025-08-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultantdb', '0006_achievement_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultant',
            options={'managed': True},
        ),
    ]
