# Generated by Django 5.0.7 on 2025-08-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultantdb', '0006_achievement_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='country_code',
            field=models.CharField(default='+91', max_length=5),
        ),
    ]