# Generated by Django 5.2.4 on 2025-08-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultantdb', '0007_add_country_code'),
        ('consultantdb', '0007_alter_consultant_options'),
    ]

    operations = [
    ]
