# Generated by Django 5.2.4 on 2025-09-10 03:57

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settingsdb', '0001_initial'),
        ('studentsdb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True)),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_bill', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi_type', models.CharField(choices=[('NONE', 'None'), ('1', '1 EMI'), ('2', '2 EMI'), ('3', '3 EMI'), ('4', '4 EMI')], default='NONE', max_length=4)),
                ('initial_payment_proof', models.ImageField(null=True, upload_to=core.utils.timestamp_upload_to)),
                ('emi_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emi_1_date', models.DateField(blank=True, null=True)),
                ('emi_1_paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emi_1_paid_date', models.DateField(blank=True, null=True)),
                ('emi_1_proof', models.ImageField(blank=True, null=True, upload_to=core.utils.timestamp_upload_to)),
                ('emi_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emi_2_date', models.DateField(blank=True, null=True)),
                ('emi_2_paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emi_2_paid_date', models.DateField(blank=True, null=True)),
                ('emi_2_proof', models.ImageField(blank=True, null=True, upload_to=core.utils.timestamp_upload_to)),
                ('emi_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emi_3_date', models.DateField(blank=True, null=True)),
                ('emi_3_paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emi_3_paid_date', models.DateField(blank=True, null=True)),
                ('emi_3_proof', models.ImageField(blank=True, null=True, upload_to=core.utils.timestamp_upload_to)),
                ('emi_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emi_4_date', models.DateField(blank=True, null=True)),
                ('emi_4_paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emi_4_paid_date', models.DateField(blank=True, null=True)),
                ('emi_4_proof', models.ImageField(blank=True, null=True, upload_to=core.utils.timestamp_upload_to)),
                ('total_pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emi_1_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_emi_1', to=settings.AUTH_USER_MODEL)),
                ('emi_2_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_emi_2', to=settings.AUTH_USER_MODEL)),
                ('emi_3_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_emi_3', to=settings.AUTH_USER_MODEL)),
                ('emi_4_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_emi_4', to=settings.AUTH_USER_MODEL)),
                ('payment_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingsdb.paymentaccount')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentsdb.student')),
            ],
        ),
    ]
