# Generated by Django 5.2.4 on 2026-01-23 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentdb', '0001_initial'),
        ('studentsdb', '0002_alter_student_pgpassout_alter_student_ugpassout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('batch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('batch_type', models.CharField(blank=True, max_length=10, null=True)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_status', models.CharField(max_length=3)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('next_emi_number', models.IntegerField(blank=True, null=True)),
                ('next_emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('consultant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('trainer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_percentage', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=10)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pending_payments', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_pending_payments', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_record', to='paymentdb.payment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsdb.student')),
            ],
        ),
    ]
