# Generated by Django 5.2.4 on 2025-07-15 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_number', models.IntegerField(choices=[(0, 'Initial'), (1, 'EMI 1'), (2, 'EMI 2'), (3, 'EMI 3'), (4, 'EMI 4')], default=0)),
                ('screenshot', models.ImageField(upload_to='payment_proofs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='paymentdb.payment')),
            ],
        ),
    ]
