# Generated by Django 5.2.4 on 2025-07-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentdb', '0002_paymentproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='emi_1_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='emi_2_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='emi_3_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='emi_4_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='initial_payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
