# Generated by Django 5.2.4 on 2026-01-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentdb', '0002_pendingpaymentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpaymentrecord',
            name='trainer_type',
            field=models.CharField(blank=True, choices=[('FT', 'Full Time'), ('FL', 'Freelancer')], max_length=2, null=True),
        ),
    ]
