# Generated by Django 5.2.4 on 2025-07-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentdb', '0003_payment_emi_1_proof_payment_emi_2_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='emi_1_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='emi_1_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='emi_2_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='emi_2_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='emi_3_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='emi_3_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='emi_4_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='emi_4_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='initial_payment_proof',
            field=models.ImageField(null=True, upload_to='payment_proofs/'),
        ),
        migrations.DeleteModel(
            name='PaymentProof',
        ),
    ]
