# Generated by Django 5.2.4 on 2025-07-22 09:48

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentdb', '0003_remove_payment_last_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='emi_1_proof',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.timestamp_upload_to),
        ),
        migrations.AlterField(
            model_name='payment',
            name='emi_2_proof',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.timestamp_upload_to),
        ),
        migrations.AlterField(
            model_name='payment',
            name='emi_3_proof',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.timestamp_upload_to),
        ),
        migrations.AlterField(
            model_name='payment',
            name='emi_4_proof',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.timestamp_upload_to),
        ),
        migrations.AlterField(
            model_name='payment',
            name='initial_payment_proof',
            field=models.ImageField(null=True, upload_to=core.utils.timestamp_upload_to),
        ),
    ]
