# Generated by Django 5.2.4 on 2025-07-23 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentdb', '0004_alter_payment_emi_1_proof_alter_payment_emi_2_proof_and_more'),
        ('settingsdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingsdb.paymentaccount'),
        ),
    ]
