# Generated by Django 5.2.4 on 2025-07-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentdb', '0005_alter_payment_payment_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='emi_type',
            field=models.CharField(choices=[('NONE', 'None'), ('1', '1 EMI'), ('2', '2 EMI'), ('3', '3 EMI'), ('4', '4 EMI')], default='NONE', max_length=4),
        ),
    ]
