# Generated by Django 5.2.4 on 2025-08-09 10:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentsdb', '0023_remove_student_course_student_course_id'),
        ('coursedb', '0005_coursemodule_has_topics_topic'),
        ('trainersdb', '0007_trainer_commercials_trainer_demo_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('batch_type', models.CharField(choices=[('Weekday', 'Weekday'), ('Weekend', 'Weekend')], default='Weekday', max_length=10)),
                ('batch_status', models.CharField(choices=[('YTS', 'Yet to Start'), ('IP', 'In Progress'), ('C', 'Completed')], default='YTS', max_length=3)),
                ('time_slot', models.JSONField(default=dict)),
                ('batch_days', models.JSONField(default=list)),
                ('batch_percentage', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='coursedb.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, related_name='batches', to='studentsdb.student')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='trainersdb.trainer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
