# Generated by Django 5.2.4 on 2025-07-17 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentsdb', '0001_initial'),
        ('trainersdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('batch_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('slot', models.CharField(choices=[('9-10.30', '9:00 AM - 10:30 AM'), ('10.30-12', '10:30 AM - 12:00 PM'), ('12-1.30', '12:00 PM - 1:30 PM'), ('3-4.30', '3:00 PM - 4:30 PM'), ('4.30-6', '4:30 PM - 6:00 PM')], max_length=20)),
                ('students', models.ManyToManyField(related_name='batches', to='studentsdb.student')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainersdb.trainer')),
            ],
        ),
    ]
