# Generated by Django 5.2.4 on 2025-07-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchdb', '0001_initial'),
        ('studentsdb', '0002_remove_student_batch_remove_student_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(related_name='batches', to='studentsdb.student'),
        ),
    ]
