# Generated by Django 5.2.4 on 2025-07-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='batch_name',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='slot',
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_type',
            field=models.CharField(choices=[('Weekday', 'Weekday'), ('Weekend', 'Weekend')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='module_name',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Spring Boot', 'Spring Boot'), ('Power BI', 'Power BI'), ('DA-Python', 'DA-Python'), ('UI/UX', 'UI/UX'), ('Dotnet', 'Dotnet'), ('C', 'C'), ('C++', 'C++')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='time_slot',
            field=models.CharField(choices=[('9-10.30', '9:00 AM - 10:30 AM'), ('10.30-12', '10:30 AM - 12:00 PM'), ('12-1.30', '12:00 PM - 1:30 PM'), ('3-4.30', '3:00 PM - 4:30 PM'), ('4.30-6', '4:30 PM - 6:00 PM')], max_length=20, null=True),
        ),
    ]
