# Generated by Django 5.2.4 on 2025-08-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='hours_per_day',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
