# Generated by Django 5.2.4 on 2025-08-13 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchdb', '0001_initial'),
        ('coursedb', '0005_coursemodule_has_topics_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='coursedb.course'),
        ),
    ]
