# Generated by Django 5.2.4 on 2025-08-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchdb', '0002_batch_hours_per_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='batch_days',
            new_name='days',
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_type',
            field=models.CharField(choices=[('WD', 'Weekday'), ('WE', 'Weekend'), ('WDWE', 'Weekday & Weekend'), ('Hybrid', 'Hybrid')], default='WD', max_length=10),
        ),
    ]
