# Generated by Django 5.2.4 on 2025-09-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchdb', '0002_batchstudent_alter_batch_students_trainerhandover_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batchstudent',
            unique_together=set(),
        ),
    ]
