# Generated by Django 5.2.4 on 2025-07-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchdb', '0002_batch_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
