# Generated by Django 5.2.4 on 2025-08-12 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchdb', '0003_rename_batch_days_batch_days_alter_batch_batch_type'),
        ('trainersdb', '0008_trainer_timing_slots_old_remove_trainer_timing_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='time_slot_old',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='batch',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_as_slot', to='trainersdb.timeslot'),
        ),
    ]
