# Generated by Django 5.2.4 on 2025-09-17 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchdb', '0003_alter_batchstudent_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='batch',
            name='hours_per_day',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
