# Generated by Django 5.2.4 on 2025-08-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchdb', '0004_batch_time_slot_old_alter_batch_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='time_slot_old',
        ),
    ]
