# Generated by Django 5.2.4 on 2025-09-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchdb', '0004_alter_batch_batch_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerhandover',
            name='handover_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
