# Generated by Django 5.2.4 on 2025-08-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchdb', '0005_remove_batch_time_slot_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='time_slot',
            field=models.JSONField(default=dict),
        ),
    ]
