# Generated by Django 3.2.12 on 2025-10-07 07:12

from django.db import migrations
from django.utils import timezone

def set_expires_at(apps, schema_editor):
    TransferRequest = apps.get_model('batchdb', 'TransferRequest')
    TrainerHandover = apps.get_model('batchdb', 'TrainerHandover')
    
    three_hours_from_now = timezone.now() + timezone.timedelta(hours=3)
    
    for request in TransferRequest.objects.filter(expires_at__isnull=True):
        request.expires_at = request.requested_at + timezone.timedelta(hours=3)
        request.save()
        
    for request in TrainerHandover.objects.filter(expires_at__isnull=True):
        request.expires_at = request.requested_at + timezone.timedelta(hours=3)
        request.save()

class Migration(migrations.Migration):

    dependencies = [
        ('batchdb', '0006_trainerhandover_expires_at_and_more'),
    ]

    operations = [
        migrations.RunPython(set_expires_at),
    ]
