# Generated by Django 5.2.4 on 2025-08-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchdb', '0006_alter_batch_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='batch',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
