# Generated by Django 5.2.4 on 2025-12-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchdb', '0007_auto_20251007_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='tentative_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
