# Generated by Django 5.2.4 on 2026-01-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchdb', '0008_batch_tentative_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('BATCH_CREATED', 'Batch Created'), ('BATCH_UPDATED', 'Batch Updated'), ('STUDENT_UPDATED', 'Student Updated'), ('STUDENT_ADDED', 'Student Added'), ('STUDENT_REMOVED', 'Student Removed'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('TRAINER_HANDOVER', 'Trainer Handover')], max_length=20),
        ),
    ]
