# Generated by Django 5.2.4 on 2026-01-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchdb', '0009_alter_batchtransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchstudent',
            name='update_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
