# Generated by Django 5.2.4 on 2026-02-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchdb', '0010_batchstudent_update_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(choices=[('YTS', 'Yet to Start'), ('IP', 'In Progress'), ('C', 'Completed'), ('H', 'Hold')], default='YTS', max_length=3),
        ),
    ]
